name: Build data

on:
  push:
    branches: [ main, master ]
  workflow_dispatch:
  schedule:
    - cron: "0 5 * * 1"  # weekly Monday 05:00 UTC

jobs:
  build:
    runs-on: ubuntu-latest
    permissions:
      contents: write
    steps:
      - uses: actions/checkout@v4
      - uses: actions/setup-python@v5
        with:
          python-version: '3.11'
      - name: Install dependencies
        run: |
          python -m pip install --upgrade pip
          pip install -r requirements.txt
      - name: Run analysis
        run: |
          python brno_climate_analysis.py
          mkdir -p data
          mv brno_climate_excel.xlsx data/brno_climate_excel.xlsx
          mv brno_climate_summary.pdf data/brno_climate_summary.pdf
      - name: Commit artifacts
        run: |
          git config user.name "github-actions[bot]"
          git config user.email "github-actions[bot]@users.noreply.github.com"
          git add data/brno_climate_excel.xlsx data/brno_climate_summary.pdf
          git commit -m "Update artifacts [skip ci]" || echo "No changes"
          git push
